### ISSUE TITLE
See list of my stories

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#50]
## User story
As an editor
I want to see the list of my stories
So that I can see which stories I have

## Tasks
- [x] Display the list from database
- [x] Add routing to different builder parts

## Acceptance Criteria
- [x] Page with the list
- [x] integrate with DynamoDB

## Designs
![image](https://user-images.githubusercontent.com/4195550/115023205-c02bc180-9ebe-11eb-9ac1-0749ab2a79d0.png)

**Comment by geek-yang** [comment]
A full list of available database services on AWS can be found [here](https://aws.amazon.com/products/databases/?nc=sn&loc=1). Among the list, DynamoDB seems to be the best candidate for our app. Amazon DynamoDB is a NoSQL key-value database that widely used for web applications. It can be easily integrated with AWS Amplify. An example of building serverless web applications with AWS Amplify can be found [here](https://docs.amplify.aws/start/getting-started/data-model/q/integration/js) (provided by Amazon). In this example, it sets up a backend and integrates that backend with a web app built with js/vue. They use GraphQL API and DynamoDB to store the user data. The whole procedure can be monitored via AWS AppSync service.

**Comment by ctwhome** [comment]
Yes, I also think that DynamoDB is the best candidate: schemaless, included in the free tier (we will never reach the limits), the native DB that runs as a platform, and there is no need for very complex queries
