### ISSUE TITLE
Example story

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#51]
## User story
As an editor
I want to get 'the' example story copied to my account if I have made a new account.
So that I can learn from the example

## Proposed work
Make sure the agriculture story is in the database and copied to the new user's account once it is verified.

In Cognito you can add a lambda function on user creation

## Tasks
- [x] Add an item (example story) in the DynamoDB when a new user sign-up and confirm.
- [x] Change the lambda function to copy story with ID 0 and give it a new unique ID
- [x] Update the story with ID 0 to have the actual content we want to be the example

## Acceptance Criteria
- [x] Each new user must have a copy of 'the' example story when they access the builder for the first time.

**Comment by geek-yang** [comment]
AWS Lambda function with post-confirmation trigger seems to be the best solution for this. Here is an official doc about how to calling DynamoDB using AWS Cognito triggers (check [here](https://docs.amplify.aws/guides/functions/cognito-trigger-lambda-dynamodb/q/platform/js). However, in our case things are much complex. We have already created the post-confirmation trigger using Lambda function, which serves to add user to a group. Since only one function can be bind to post-confirmation trigger, we can not simply add a function to create an item in DynamoDB to the existing Lambda function. When we do it in this way, with "amplify push" we will receive an error. It is an known [issue](https://github.com/aws-amplify/amplify-cli/issues/4568). So far, it seems to me the best solution is, invoke a child Lambda function (create an example story) inside the parent Lambda function (add user to group). But this looks a bit nasty...Please leave a message if anyone has a good solution for it.

**Comment by geek-yang** [comment]
By adding the code for creating an example story directly inside the Lambda function of adding a user to a group, when executing "amplify push" an error will occur, which reads: 
`UPDATE_FAILED               HostedUIProvidersCustomResourceInputs                       Custom::LambdaCallout      Mon May 03 2021 16:27:59 GMT+0200 (Central European Summer Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/05/03/[$LATEST]677e6c1582f844c18bfe996a9a503d4e (RequestId: 53d43298-8135-4fc8-a29c-d95f7d384632)`

`UPDATE_FAILED               authreceipt09937347        AWS::CloudFormation::Stack Mon May 03 2021 16:28:09 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:eu-central-1:204861241826:stack/amplify-receipt-dev-145534-authreceipt09937347-35BZX60T934U/8a311950-a1dd-11eb-a109-0a082239d27a was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].`

**Comment by geek-yang** [comment]
Error fixed by removing the google authenticator (which was created when initialized the amplify but never used).

**Comment by bpmweel** [comment]
To enable copying the story and pages the PostConfirmation function needed access to the CognitoDB the straightforward way of adding a dependency to this resulted in a circular dependency:
```bash
Circular dependency between resources: [UpdateRolesWithIDPFunctionOutputs, apireceiptAPI, functionreceipt09937347PostConfirmation, authreceipt09937347, UpdateRolesWithIDPFunction]
An error occurred during the push operation: Circular dependency between resources: [UpdateRolesWithIDPFunctionOutputs, apireceiptAPI, functionreceipt09937347PostConfirmation, authreceipt09937347, UpdateRolesWithIDPFunction]
```

After trying various options we chose to extract the copying to a separate lambda function (`addExampleStory`) and adding a dependency to this 
function to PostConfirmation. This resulted in thee same circular dependency however.
```
Circular dependency between resources: [functionaddExampleStory, UpdateRolesWithIDPFunctionOutputs, apireceiptAPI, functionreceipt09937347PostConfirmation, authreceipt09937347, UpdateRolesWithIDPFunction]
An error occurred during the push operation: Circular dependency between resources: [functionaddExampleStory, UpdateRolesWithIDPFunctionOutputs, apireceiptAPI, functionreceipt09937347PostConfirmation, authreceipt09937347, UpdateRolesWithIDPFunction]
```

**Comment by bpmweel** [comment]
I finally found that there is a new option for amplify that tries to prevent circular dependencies here: https://github.com/aws-amplify/amplify-cli/issues/4568#issuecomment-858809588

I have implemented this in pull request: https://github.com/RECEIPT-H2020/terriajs/pull/83

There is still 1 small issue, it seems this breaks the automatic setting of sending a confirmation email:  https://github.com/aws-amplify/amplify-cli/issues/4568#issuecomment-872549532 but this is easily fixed in the aws cognito ui.
