### ISSUE TITLE
Redirect to the login page if the user is not logged in when editing

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#84]
## User story
As an editor
When accessing directly to the builder to edit a story via a link, the application should redirect me to the login page.

## Proposed work
Routing changes

## Tasks
- [ ] Change routing so that users get redirected to the login page if authentication is needed.
- [ ] Make sure the original link is accessed after logging in.

## Acceptance Criteria
- [ ] Open a direct link to a story in an incognito window, if redirection to the login screen is done (and upon logging in, the desired link is accessed again), job done.
